steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Training Image'
    args: [
      'build',
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/training-image:$SHORT_SHA',
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/training-image:latest',
      '-f', './dockerfiles/train.dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Evaluation Image'
    args: [
      'build',
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/eval-image:$SHORT_SHA',
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/eval-image:latest',
      '-f', './dockerfiles/evaluate.dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Download Data'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # 1. Create the exact nested folder structure
        mkdir -p /workspace/data/processed

        # 2. List the bucket to see what is actually there (for your logs)
        echo "Listing Bucket Contents:"
        gsutil ls gs://mlops_bucket_group_77/data/processed/

        # 3. Copy contents using a wildcard to ensure they go INTO the processed folder
        # We use quotes around the wildcard path to prevent shell expansion issues
        gsutil -m cp -r "gs://mlops_bucket_group_77/data/processed/*" /workspace/data/processed/

        # 4. Debug: Verify what happened
        echo "Listing Workspace Contents after download:"
        ls -R /workspace/data

  - name: '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/training-image:$SHORT_SHA'
    id: 'Run Training'
    args: ['--dataset', 'cloud']
    env:
      - 'WANDB_MODE=offline'
      - 'WANDB_PROJECT=debug-build'
      - 'WANDB_ENTITY=debug-user'

  - name: '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/eval-image:$SHORT_SHA'
    id: 'Run Evaluation'
    args: ['--dataset', 'cloud']

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Upload Model'
    args: ['cp', '/workspace/model.pth', 'gs://mlops_bucket_group_77/models/model-$SHORT_SHA.pth']

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/training-image:$SHORT_SHA'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/training-image:latest'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/eval-image:$SHORT_SHA'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/eval-image:latest'

substitutions:
  _REGION: 'europe-west1'
  _REPO_NAME: 'group-77-project'

options:
  logging: CLOUD_LOGGING_ONLY
