steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Frontend Image"
    args:
      [
        "build",
        "-t",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/frontend-image:$SHORT_SHA",
        "-t",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/frontend-image:latest",
        "-f",
        "./dockerfiles/frontend.dockerfile",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "Push Frontend Image"
    args:
      [
        "push",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/frontend-image:$SHORT_SHA",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Frontend"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail

        API_URL=$(gcloud run services describe fake-art-api \
          --region "$_REGION" \
          --format='value(status.url)')

        echo "Deploying frontend with BACKEND_URL=${API_URL}"

        gcloud run deploy fake-art-frontend \
          --image "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/frontend-image:$SHORT_SHA" \
          --region "$_REGION" \
          --platform managed \
          --allow-unauthenticated \
          --memory "2Gi" \
          --cpu "1" \
          --set-env-vars "BACKEND_URL=${API_URL}"

substitutions:
  _REGION: "europe-west1"
  _REPO_NAME: "group-77-project"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/wandb-api-key/versions/latest
      env: "WANDB_API_KEY"

options:
  logging: CLOUD_LOGGING_ONLY
